# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./exemplo.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/566e1d02-76bf-4f49-8f4b-1a6c4dc4e6ec/transcription
Content-Type: application/json

{
  "prompt": "motivation"
}